export const MESSAGE_BOARDS_GET_REQUEST = 'MESSAGE_BOARDS_GET_REQUEST'
export const MESSAGE_BOARDS_GET_SUCCESS = 'MESSAGE_BOARDS_GET_SUCCESS'
export const MESSAGE_BOARDS_GET_FAIL = 'MESSAGE_BOARDS_GET_FAIL'
