export const ALLPOSTS_GET_REQUEST = 'ALLPOSTS_GET_REQUEST'
export const ALLPOSTS_GET_SUCCESS = 'ALLPOSTS_GET_SUCCESS'
export const ALLPOSTS_GET_FAIL = 'ALLPOSTS_GET_FAIL'

export const MYPOSTS_GET_REQUEST = ' MYPOSTS_GET_REQUEST'
export const MYPOSTS_GET_SUCCESS = ' MYPOSTS_GET_SUCCESS'
export const MYPOSTS_GET_FAIL = ' MYPOSTS_GET_FAIL'

export const MYPOSTS_DELETE_REQUEST = ' MYPOSTS_DELETE_REQUEST'
export const MYPOSTS_DELETE_SUCCESS = ' MYPOSTS_DELETE_SUCCESS'
export const MYPOSTS_DELETE_FAIL = ' MYPOSTS_DELETE_FAIL'

export const MYPOSTS_UPDATE_REQUEST = ' MYPOSTS_UPDATE_REQUEST'
export const MYPOSTS_UPDATE_SUCCESS = ' MYPOSTS_UPDATE_SUCCESS'
export const MYPOSTS_UPDATE_FAIL = ' MYPOSTS_UPDATE_FAIL'
