export const PROFILE_GET_REQUEST = 'PROFILE_GET_REQUEST'
export const PROFILE_GET_SUCCESS = 'PROFILE_GET_SUCCESS'
export const PROFILE_GET_FAIL = 'PROFILE_GET_FAIL'

export const PROFILE_ADD_MESSAGEBOARD_REQUEST =
	'PROFILE_ADD_MESSAGEBOARD_REQUEST'
export const PROFILE_ADD_MESSAGEBOARD_SUCCESS =
	'PROFILE_ADD_MESSAGEBOARD_SUCCESS'
export const PROFILE_ADD_MESSAGEBOARD_FAIL = 'PROFILE_ADD_MESSAGEBOARD_FAIL'
