export const ALLTRIPS_GET_REQUEST = 'ALLTRIPS_GET_REQUEST'
export const ALLTRIPS_GET_SUCCESS = 'ALLTRIPS_GET_SUCCESS'
export const ALLTRIPS_GET_FAIL = 'ALLTRIPS_GET_FAIL'

export const MYTRIPS_GET_REQUEST = ' MYTRIPS_GET_REQUEST'
export const MYTRIPS_GET_SUCCESS = ' MYTRIPS_GET_SUCCESS'
export const MYTRIPS_GET_FAIL = ' MYTRIPS_GET_FAIL'

export const MYTRIPS_DELETE_REQUEST = ' MYTRIPS_DELETE_REQUEST'
export const MYTRIPS_DELETE_SUCCESS = ' MYTRIPS_DELETE_SUCCESS'
export const MYTRIPS_DELETE_FAIL = ' MYTRIPS_DELETE_FAIL'

export const MYTRIPS_UPDATE_REQUEST = ' MYTRIPS_UPDATE_REQUEST'
export const MYTRIPS_UPDATE_SUCCESS = ' MYTRIPS_UPDATE_SUCCESS'
export const MYTRIPS_UPDATE_FAIL = ' MYTRIPS_UPDATE_FAIL'

export const MYTRIPS_LEAVE_REQUEST = ' MYTRIPS_LEAVE_REQUEST'
export const MYTRIPS_LEAVE_SUCCESS = ' MYTRIPS_LEAVE_SUCCESS'
export const MYTRIPS_LEAVE_FAIL = ' MYTRIPS_LEAVE_FAIL'

export const MYTRIPS_JOIN_REQUEST = ' MYTRIPS_JOIN_REQUEST'
export const MYTRIPS_JOIN_SUCCESS = ' MYTRIPS_JOIN_SUCCESS'
export const MYTRIPS_JOIN_FAIL = ' MYTRIPS_JOIN_FAIL'
