export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGIN_LOGOUT = 'USER_LOGIN_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_GET_FRIENDS_REQUEST = 'USER_GET_FRIENDS_REQUEST'
export const USER_GET_FRIENDS_SUCCESS = 'USER_GET_FRIENDS_SUCCESS'
export const USER_GET_FRIENDS_FAIL = 'USER_GET_FRIENDS_FAIL'

export const USER_REJECT_FRIEND_REQUEST = 'USER_REJECT_FRIEND_REQUEST'
export const USER_REJECT_FRIEND_SUCCESS = 'USER_REJECT_FRIEND_SUCCESS'
export const USER_REJECT_FRIEND_FAIL = 'USER_REJECTE_FRIEND_FAIL'

export const USER_ACCEPT_FRIEND_REQUEST = 'USER_ACCEPT_FRIEND_REQUEST'
export const USER_ACCEPT_FRIEND_SUCCESS = 'USER_ACCEPT_FRIEND_SUCCESS'
export const USER_ACCEPT_FRIEND_FAIL = 'USER_ACCEPT_FRIEND_FAIL'

export const USER_REQUEST_FRIEND = 'USER_REQUEST_FRIEND'
export const USER_REQUEST_FRIEND_SUCCESS = 'USER_REQUEST_FRIEND_SUCCESS'
export const USER_REQUEST_FRIEND_FAIL = 'USER_REQUEST_FRIEND_FAIL'

export const USER_GET_MESSAGEBOARDS_REQUEST = 'USER_GET_MESSAGEBOARDS_REQUEST'
export const USER_GET_MESSAGEBOARDS_FAIL = 'USER_GET_MESSAGEBOARDS_FAIL'
export const USER_GET_MESSAGEBOARDS_SUCCESS = 'USER_GET_MESSAGEBOARDS_SUCCESS'
