PUT https://together-trek-testing.herokuapp.com/users/6047fa7173acb538b8de4f29
Content-Type: application/json

{
"location": {},
"post_ids": ["604b250ff8ea280015d74252", "604b2524f8ea280015d74255"],
"trip_ids": [ ],
"message_board_ids": [ ],
"friend_ids": [ ],
"username": "TestWebFront",
"password": "password",
"email": "testweb@front.end",
"birthdate": "2001-01-01T00:00:00.000Z",
"gender": "Male",
"first_name": "Front",
"last_name": "Test",
"__v": 0
}