# This workflow runs our postman Full Test Suite collection against code
# that is being pull requested to main

name: Postman Test Run

on:
  pull_request:
    branches:
      - main

jobs:
  postman:
    name: Postman test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install node packages
        run: npm install
      - name: Install newman
        run: npm install -g newman
      - name: Start api
        run: npm start
      - name: Run newman
        run: newman run ./app/tests/Full_Test_Suite.postman_collection.json
